name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.0-43.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/s1Great-Juices.jpg
    - images/s2Great-Frozen.jpg
    - images/96529980_132672218392298_593711703196172288_n.png
    - images/برجر.jpg
    - images/بسطرمه.jpg
    - images/بيفى.jpg
    - images/رومى مدخن.jpg
    - images/سجق شرقى.jpg
    - images/سلامى بقرى مطبوخ مدخن.jpg
    - images/سلامى رول.jpg
    - images/سمبوسك باللحمه.jpg
    - images/سمبوسه جبنه نعناع.jpg
    - images/فرانكفورتر بقرى.jpg
    - images/كفته بقرى.jpg
    - images/كوكتيل سوسيس بقرى.jpg
    - images/لانشون بقرى ساده.jpg
    - images/لحم مفروم خشن.jpg
    - images/لانشون فراخ.jpg
    - images/هوت دوج.jpg
