import '../models/product.dart';

List<Product> products = [
  // ignore: prefer_const_constructors
  Product(
    id: 1,
    price: 10,
    title: "برجر",
    subtitle: "برجر",
    imageurl: "images/برجر.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 2,
    price: 10,
    title: "بسطرمه",
    subtitle: "بسطرمه",
    imageurl: "images/بسطرمه.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 3,
    price: 10,
    title: "بيفى",
    subtitle: "بيفى",
    imageurl: "images/بيفى.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 4,
    price: 10,
    title: "رومى مدخن",
    subtitle: "رومى مدخن",
    imageurl: "images/رومى مدخن.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 5,
    price: 10,
    title: "سجق شرقى",
    subtitle: "سجق شرقى",
    imageurl: "images/سجق شرقى.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 6,
    price: 10,
    title: "سلامى بقرى مطبوخ مدخن",
    subtitle: "سلامى بقرى مطبوخ مدخن",
    imageurl: "images/سلامى بقرى مطبوخ مدخن.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 7,
    price: 10,
    title: "سلامى رول",
    subtitle: "سلامى رول",
    imageurl: "images/سلامى رول.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 8,
    price: 10,
    title: "سمبوسك باللحمه",
    subtitle: "سمبوسك باللحمه",
    imageurl: "images/سمبوسك باللحمه.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 9,
    price: 10,
    title: "سمبوسك جبنه بالنعناع",
    subtitle: "سمبوسك جبنه بالنعناع",
    imageurl: "images/سمبوسه جبنه نعناع.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 10,
    price: 10,
    title: "فرانكفورتر بقرى",
    subtitle: "فرانكفورتر بقرى",
    imageurl: "images/فرانكفورتر بقرى.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 11,
    price: 10,
    title: "كفته بقرى",
    subtitle: "كفته بقرى",
    imageurl: "images/كفته بقرى.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 12,
    price: 10,
    title: "كوكتيل سوسيس بقرى",
    subtitle: "كوكتيل سوسيس بقرى",
    imageurl: "images/كوكتيل سوسيس بقرى.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 13,
    price: 10,
    title: "لانشون بقرى ساده",
    subtitle: "لانشون بقرى ساده",
    imageurl: "images/لانشون بقرى ساده.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 14,
    price: 10,
    title: "لحم مفروم خشن",
    subtitle: "لحم مفروم خشن",
    imageurl: "imges/لحم مفروم خشن.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 15,
    price: 10,
    title: "لانشون فراخ",
    subtitle: "لانشون فراخ",
    imageurl: "images/لانشون فراخ.jpg",
    description: "fjfkfk",
  ),
  Product(
    id: 16,
    price: 10,
    title: "هوت دوج",
    subtitle: "هوت دوج",
    imageurl: "images/هوت دوج.jpg",
    description: "fjfkfk",
  ),
];
